application: lt-talk-emailer 
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on 

handlers:

- url: /static
  static_dir: static 

- url: /auth/.*
  login: required
  
- url: /_ah/login_required
  script: do_openid_login.app
  
- url: .*
  script: main.app

